### ISSUE TITLE
Example is not working.

### ISSUE THREAD

**Issue by Subtixx** [dovker/Monogame.ImGui#1]
When using the library like in the example:

> System.InvalidOperationException: "No Graphics Device Service"

When putting the creation of the renderer below the graphics one:

> System.ArgumentNullException: "The GraphicsDevice must not be null when creating new resources.
Parametername: graphicsDevice"

The creation must be in the Initialize function of the class.

This works:
```
protected override void Initialize()
        {
            GuiRenderer = new ImGUIRenderer(this).Initialize().RebuildFontAtlas();

            base.Initialize();
        }
```

**Comment by dovker** [comment]
I fixed the example, thanks for noticing this (I know it's been over a year, sorry for that haha)
