### ISSUE TITLE
Alternative to Monogame.ImGui

### ISSUE THREAD

**Issue by tsMezotic** [dovker/Monogame.ImGui#9]
As this project is seemingly discontinued, I have created a new alternative.

https://github.com/Mezo-hx/Monogame.ImGuiNet

Note: The NuGet package is out of date and isn't working, I'll be updating it with the working version tomorrow! as well as putting out the small source code for it (which is a SuperSet of ImGui.Net's XNA example)

**Comment by tsMezotic** [comment]
the NuGet package has been updated, as well as the github repo... So, it should now be usable!

**Comment by dovker** [comment]
- Added this alternative to the description! If anyone continues to add pull requests to this project I will merge them so that current users could get some updates, but choosing an actively developed alternative is always a better option!
